### PR TITLE
Use GFM for markdown

### LINKED ISSUE #16: header and footer in README.md
The README.md does not render correctly here

https://homalg-project.github.io/SubcategoriesForCAP/

while it does there

https://homalg-project.github.io/LoopIntegrals/

Does this have to do with header/footer in the former?

### PR DESCRIPTION
**Pull request by zickgraf**
@mohamed-barakat please test if this correctly sets the markdown processor to `GFM` in your packages.

Fixes #16.

### CODE REVIEW

**Review by mohamed-barakat — APPROVED** [review]

**Comment by mohamed-barakat** [comment]
Works for me. Thank you very much.

**Comment by mohamed-barakat** [comment]
I am searching for a GitHub compatible markdown that also works with Jekyll. This would be the ideal solution.

**Comment by zickgraf** [comment]
> I am searching for a GitHub compatible markdown that also works with Jekyll.

See https://github.com/gap-system/GitHubPagesForGAP/pull/20#issuecomment-698462924 for my research in this direction.

**Comment by mohamed-barakat** [comment]
> See [gap-system/GitHubPagesForGAP#20 (comment)](https://github.com/gap-system/GitHubPagesForGAP/pull/20#issuecomment-698462924) for my research in this direction.

Thanks for the hint.

**Pull request merged**
