### PR TITLE
Switch from https://codecov.io -> https://app.codecov.io

### PR DESCRIPTION
**Pull request by mohamed-barakat**
resolves https://github.com/homalg-project/PackageJanitor/issues/121

### CODE REVIEW

**Comment by zickgraf** [comment]
Did you have any concrete problems with the old URL? When creating a badge for a package (e.g. https://app.codecov.io/gh/homalg-project/CAP_project/settings/badge) Codecov officially links to https://codecov.io/, so I would not like to deviate from this except if it leads to concrete problems (in which case we should also ping codecov about this).

**Comment by mohamed-barakat** [comment]
> Did you have any concrete problems with the old URL?

Yes, many. All links to the CI referring to https://codecov.io/ did not work yesterday. When they worked they sometimes showed the old-style codecov pages but sometimes also forwarded to the new-style app.codecov.

> When creating a badge for a package (e.g. https://app.codecov.io/gh/homalg-project/CAP_project/settings/badge) Codecov officially links to https://codecov.io/, so I would not like to deviate from this except if it leads to concrete problems (in which case we should also ping codecov about this).

For the badges I agree, but it seems that codecov is otherwise forwarding to app.codecov.

**Comment by mohamed-barakat** [comment]
For example

https://codecov.io/gh/homalg-project/CategoricalTowers

redirects to

https://app.codecov.io/gh/homalg-project/CategoricalTowers

But this redirection does not always work. Yesterday I got no-page found most of the time, sometimes I got the old page, and sometimes the redirection worked.

**Comment by zickgraf** [comment]
> For the badges I agree, but it seems that codecov is otherwise forwarding to app.codecov.

That's the code I get when creating a badge on https://app.codecov.io/gh/homalg-project/CAP_project/settings/badge:
```
[![codecov](<URL_OF_SVG>)](https://codecov.io/gh/homalg-project/CAP_project)
```
So for me it looks like Codecov actually recommends linking to `https://codecov.io/...` and the redirect is an implementation detail which might change at any time.

**Review by zickgraf — APPROVED** [review]
As discussed, errors might occur with both the `app` and the plain URL. However, by linking to the `app` URL, we can at least (probably) rule out that sometimes the old version gets displayed.

**Pull request merged**
