### PR TITLE
Revert "updated FunctorCategories"

### PR DESCRIPTION
**Pull request by mohamed-barakat**
This reverts commit 5b79eb4d4f10522c16302496e63e4977b1aeb33f.

I still need Limit/Colimit in the notebooks

### CODE REVIEW

**Comment by zickgraf** [comment]
If you only need CategoryConstructor in the notebooks it should suffice to add it to `ci_additional_repositories` (and then explicitly load it in the notebooks).

**Comment by mohamed-barakat** [comment]
> If you only need CategoryConstructor in the notebooks, it should suffice to add it to `ci_additional_repositories` (and then explicitly load it in the notebooks).

I want the users to load exactly one package. I have to think of a different solution.

**Comment by zickgraf** [comment]
> Somehow the site.yml file is broken

The site.yml was fine but I broke the Tests.yml template. Fixed in 6cd7fbe33f027aa04561440b3d8b0d4c9d7d8f91.

**Comment by mohamed-barakat** [comment]
> The site.yml was fine but I broke the Tests.yml template. Fixed in [6cd7fbe](https://github.com/homalg-project/PackageJanitor/commit/6cd7fbe33f027aa04561440b3d8b0d4c9d7d8f91).

Ah, thanks for the fix.

**Pull request merged**
