### PR TITLE
started CategoricalTowers with one new package

### PR DESCRIPTION
**Pull request by mohamed-barakat**

### CODE REVIEW

**Comment by zickgraf** [comment]
Shall I merge or shall I wait until the dust has settled?

Regarding the name "CategoricalTowers": Is this a term which people understand? Maybe "TowersOfCategories" would be easier to understand.

And some questions regarding the definition of the meta-repo respectively the term "tower":
1. Does the term "tower" refer to a composition of category constructors (i.e. it is itself a category constructor) or does it refer to a category constructed by applying multiple category constructors?
2. Is a single category constructor a tower (of height 1) in the sense of the meta-repo? 
3. Do towers in the sense of the meta-repo always have to start with a primitive category constructor?

**Comment by mohamed-barakat** [comment]
> Shall I merge or shall I wait until the dust has settled?

You can wait until we discuss the details. The PR is primarily for your info.

> Regarding the name "CategoricalTowers": Is this a term which people understand? Maybe "TowersOfCategories" would be easier to understand.

This was one of the points I wanted to discuss with you. The description is `Towers of category constructors`. But I also like your suggestion.

> And some questions regarding the definition of the meta-repo respectively the term "tower":
> 
> 1. Does the term "tower" refer to a composition of category constructors (i.e. it is itself a category constructor) or does it refer to a category constructed by applying multiple category constructors?

The first.

> 2. Is a single category constructor a tower (of height 1) in the sense of the meta-repo?

Any constructor can be itself a tower.

> 3. Do towers in the sense of the meta-repo always have to start with a primitive category constructor?

No. A tower can be thought of as a new category constructor built out of existing ones. So a tower can be applied to a primitive category, to itself, or to another tower.

**Comment by zickgraf** [comment]
Okay, perfect :-) I see that this will get quite intricate, so yes, we should continue the discussion verbally.

One note for the discussion: I think the definition of "tower" above differs from the definition of "tower" in @kamalsaleh's thesis. (which is not a problem, just a thing we should keep in mind I think)

**Comment by kamalsaleh** [comment]
For future reference, in the thesis, I defined a **tower of categories** as a category that was created by composing two or more category constructors.

**Comment by mohamed-barakat** [comment]
This PR generates in `homalg-project.github.io` the permalink `pkg/FiniteCocompletion.html` but not `pkg/PreSheaves.html`. I don't understand where the problem lies.

**Comment by zickgraf** [comment]
> This PR generates in `homalg-project.github.io` the permalink `pkg/FiniteCocompletion.html` but not `pkg/PreSheaves.html`. I don't understand where the problem lies.

You have to add PreSheaves to the target "homalg-project.github.io", just like you did with FiniteCocompletion.

**Comment by mohamed-barakat** [comment]
> You have to add PreSheaves to the target "homalg-project.github.io", just like you did with FiniteCocompletion.

Oh yes. It was late yesterday :)

**Comment by mohamed-barakat** [comment]
From my side, this PR is ready for merging.

**Comment by zickgraf** [comment]
Is there a reason why you have not deleted the non-meta packages from `site.yml`?

**Comment by mohamed-barakat** [comment]
They can all be deleted in a subsequent PR.

**Comment by zickgraf** [comment]
Then please make sure the diff does not contain changes to the non-meta packages.

**Comment by mohamed-barakat** [comment]
> Then please make sure the diff does not contain changes to the non-meta packages.

I don't understand your request :)

**Comment by zickgraf** [comment]
> > Then please make sure the diff does not contain changes to the non-meta packages.
> 
> I don't understand your request :)

The diff showed changes to non-meta packages. I don't know why, but I did not want to investigate and/or review changes which were planned be deleted anyway.

**Comment by mohamed-barakat** [comment]
It was a missing rebase.

**Pull request merged**
